receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: 0.0.0.0:9464
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlp/phoenix:
    endpoint: phoenix:4317
    tls:
      insecure: true

processors:
  batch:
  filter/phoenix_openinference_only:
    error_mode: ignore
    traces:
      span:
        - attributes["openinference.span.kind"] == nil

service:
  pipelines:
    traces/tempo:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    traces/phoenix:
      receivers: [otlp]
      processors: [filter/phoenix_openinference_only, batch]
      exporters: [otlp/phoenix]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
